### ISSUE TITLE
add linter

### ISSUE THREAD

**Issue by margielamadman** [quinnmil/summit#19]
use airbnb style guide

**Comment by quinnmil** [comment]
I'm thinking we should go with [StandardJS](https://standardjs.com/) to use and add to project, (no config files needed) and it's a good, clean standard. Has a CLI tool and vim linter as well.

**Comment by margielamadman** [comment]
Install Standard:
`npm install standard --global`

Add this extension to VSCode: [StandardJS](https://marketplace.visualstudio.com/items?itemName=chenxsan.vscode-standardjs)

**Comment by quinnmil** [comment]
@margielamadman Do you want to make one big "lint files" issue or just lint files as we come across them? Looking to close this issue since we have chosen a linter and are both setup to use it.
