### ISSUE TITLE
Initialize front-end framework

### ISSUE THREAD

**Issue by quinnmil** [quinnmil/summit#7]
I'm using Express / Node for the backend, the Pug templating engine. I think we’re going to want to use a real front end framework to make the site as nice as possible, and the earlier was can pick one and start learning it the better. Need to do some research and. I know that [vue](https://vuejs.org) popular and well regarded, but since there are **so** many frontend frameworks, I think it's worth doing some research. 

After picking one, we should initialize a landing / home page into the app. This might require some directory restructuring, so I'd like to have this done earlier than later.

**Comment by margielamadman** [comment]
Let's go with a MERN stack. Mongodb, Express.js, React, and Node.js
